# Numerical Python (NumPy)

In [76]:
import numpy as np

In [77]:
#convert list to numpy arry
mylist = [1, 2, 3,4,5,6,7,8,9,10]
x = np.array(mylist)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
#Or just pass in a list directly
y = np.array([1, 2, 3,4,5,6,7,8,9,10])
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
#for multtidimensional arrays
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [80]:
#shape provides the dimension of the matix
m.shape

(2, 3)

In [81]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [82]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [83]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [84]:
o=o.reshape(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [85]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [86]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
#eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
#diagonal matrix
np.diag(y)

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [89]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [90]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

# Combining Arrays

In [91]:
p = np.ones((2, 3), float)
p

array([[1., 1., 1.],
       [1., 1., 1.]])

In [92]:
#it will work the same in this way also
p = np.ones([2, 3], float)
p

array([[1., 1., 1.],
       [1., 1., 1.]])

In [93]:
#vertical stacking
np.vstack([p, 2*p])

array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [94]:
#horizontal stacking
np.hstack([p, 2*p])

array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.]])

<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [95]:
# x=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
#y=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
x.dot(y)

385

In [96]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


In [98]:
z = np.array([y, y**2])
z

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]])

In [99]:
z.shape

(2, 10)

In [100]:
#Use `.T` to get the transpose.
z.T

array([[  1,   1],
       [  2,   4],
       [  3,   9],
       [  4,  16],
       [  5,  25],
       [  6,  36],
       [  7,  49],
       [  8,  64],
       [  9,  81],
       [ 10, 100]])

In [101]:
z.T.shape

(10, 2)

In [102]:
z.dtype

dtype('int32')

In [103]:
#Use `.astype` to cast to a specific type.
z = z.astype('f')
z.dtype

dtype('float32')

# Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [104]:
a = np.array([-4, -2, 1, 3, 5,78,84,8,8,7,8,77])

In [105]:
a.sum()

273

In [106]:
a.max()

84

In [107]:
a.min()

-4

In [108]:
a.mean()

22.75

In [109]:
a.std()

33.10872241570188

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [110]:
a.argmax()

6

In [111]:
a.argmin()

0

In [112]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [113]:
s[0], s[4], s[-1]

(0, 16, 144)

In [114]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [115]:
#Use negatives to count from the back.
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [116]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [117]:
#Use bracket notation to slice: `array[row, column]`
r[2, 2]

14

In [118]:
r[3, 3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [119]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [120]:
r[-1, ::2]

array([30, 32, 34])

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [121]:
r[r > 30]

array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [122]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
## Copying Data

In [123]:
#Be careful with copying and modifying arrays in NumPy!
#r2 is a slice of r

r2 = r[:4,:4]
r2

array([[ 0,  1,  2,  3],
       [ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [18, 19, 20, 21]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [124]:
r2[:] = 0
r2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [125]:
#`r` has also been changed!
r

array([[ 0,  0,  0,  0,  4,  5],
       [ 0,  0,  0,  0, 10, 11],
       [ 0,  0,  0,  0, 16, 17],
       [ 0,  0,  0,  0, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [126]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  0,  4,  5],
       [ 0,  0,  0,  0, 10, 11],
       [ 0,  0,  0,  0, 16, 17],
       [ 0,  0,  0,  0, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Now when r_copy is modified, r will not be changed.

In [127]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  0  4  5]
 [ 0  0  0  0 10 11]
 [ 0  0  0  0 16 17]
 [ 0  0  0  0 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<br>
### Iterating Over Arrays

In [128]:
test = np.random.randint(0, 10, (4,5))
test

array([[4, 0, 5, 1, 4],
       [3, 8, 2, 2, 6],
       [2, 6, 7, 2, 7],
       [4, 7, 9, 3, 5]])

<br>
Iterate by row:

In [129]:
for row in test:
    print(row)

[4 0 5 1 4]
[3 8 2 2 6]
[2 6 7 2 7]
[4 7 9 3 5]


<br>
Iterate by index:

In [130]:
for i in range(len(test)):
    print(test[i])

[4 0 5 1 4]
[3 8 2 2 6]
[2 6 7 2 7]
[4 7 9 3 5]


In [131]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [4 0 5 1 4]
row 1 is [3 8 2 2 6]
row 2 is [2 6 7 2 7]
row 3 is [4 7 9 3 5]


<br>
Use `zip` to iterate over multiple iterables.

In [132]:
test2 = test**2
test2

array([[16,  0, 25,  1, 16],
       [ 9, 64,  4,  4, 36],
       [ 4, 36, 49,  4, 49],
       [16, 49, 81,  9, 25]], dtype=int32)

In [133]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[4 0 5 1 4] + [16  0 25  1 16] = [20  0 30  2 20]
[3 8 2 2 6] + [ 9 64  4  4 36] = [12 72  6  6 42]
[2 6 7 2 7] + [ 4 36 49  4 49] = [ 6 42 56  6 56]
[4 7 9 3 5] + [16 49 81  9 25] = [20 56 90 12 30]
